//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calanthe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public int NumberLesson { get; set; }
        public string StatusTeoria { get; set; }
        public string StatusPractic { get; set; }
    
        public virtual PracticalLesson PracticalLesson { get; set; }
        public virtual Student Student { get; set; }
        public virtual TheoreticalLesson TheoreticalLesson { get; set; }
    }
}
